/****** Object:  Database [TestResearchDB]    Script Date: 5/15/2024 7:50:41 PM ******/
CREATE DATABASE [TestResearchDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestResearchDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TestResearchDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestResearchDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TestResearchDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestResearchDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestResearchDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestResearchDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestResearchDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestResearchDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestResearchDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestResearchDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestResearchDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestResearchDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestResearchDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestResearchDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestResearchDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestResearchDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestResearchDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestResearchDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestResearchDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestResearchDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestResearchDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestResearchDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestResearchDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestResearchDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestResearchDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestResearchDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestResearchDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TestResearchDB] SET  MULTI_USER 
GO

ALTER DATABASE [TestResearchDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestResearchDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestResearchDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestResearchDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TestResearchDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestResearchDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TestResearchDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [TestResearchDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [TestResearchDB] SET  READ_WRITE 
GO



/********TABLE CREATION START**********/

USE [TestResearchDB]
GO

/****** Object:  Table [dbo].[USERS]    Script Date: 5/15/2024 7:52:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[USERS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[USER_NAME] [nvarchar](100) NOT NULL,
	[PASSWORD] [nvarchar](100) NOT NULL,
	[ENC_PASSWORD] [nvarchar](max) NOT NULL,
	[USER_ADDRESS] [nvarchar](max) NULL,
	[UPLOADED_IMG] [nvarchar](max) NULL,
	[FULL_NAME] [nvarchar](200) NULL,
 CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


USE [TestResearchDB]
GO

/****** Object:  Table [dbo].[SURVEY_FORM_HEAD]    Script Date: 5/15/2024 7:52:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SURVEY_FORM_HEAD](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[OWNER_NAME] [nvarchar](max) NOT NULL,
	[SHOP_NAME] [nvarchar](max) NOT NULL,
	[OWNER_EMAIL] [nvarchar](200) NOT NULL,
	[ADDRESS] [nvarchar](max) NULL,
	[PHONE_NUMBER] [nvarchar](100) NULL,
	[SURVEY_USER_ID] [bigint] NOT NULL,
	[SURVEY_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_SURVEY_FORM] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SURVEY_FORM_HEAD]  WITH CHECK ADD  CONSTRAINT [FK_SURVEY_FORM_HEAD_USERS] FOREIGN KEY([SURVEY_USER_ID])
REFERENCES [dbo].[USERS] ([ID])
GO

ALTER TABLE [dbo].[SURVEY_FORM_HEAD] CHECK CONSTRAINT [FK_SURVEY_FORM_HEAD_USERS]
GO


USE [TestResearchDB]
GO

/****** Object:  Table [dbo].[SURVEY_FORM_DETAILS]    Script Date: 5/15/2024 7:53:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SURVEY_FORM_DETAILS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[SURVEY_FORM_HEAD_ID] [bigint] NOT NULL,
	[DEVICE_NAME] [nvarchar](100) NULL,
	[DEVICE_CODE] [nvarchar](max) NULL,
	[CREATED_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_SURVEY_FORM_DETAILS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[SURVEY_FORM_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_SURVEY_FORM_DETAILS_SURVEY_FORM_HEAD] FOREIGN KEY([SURVEY_FORM_HEAD_ID])
REFERENCES [dbo].[SURVEY_FORM_HEAD] ([ID])
GO

ALTER TABLE [dbo].[SURVEY_FORM_DETAILS] CHECK CONSTRAINT [FK_SURVEY_FORM_DETAILS_SURVEY_FORM_HEAD]
GO


/***********CREATE STORED PROCEDURE START*************/

USE [TestResearchDB]
GO

/****** Object:  StoredProcedure [dbo].[INSERT_USERS_DETAILS]    Script Date: 5/15/2024 7:53:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[INSERT_USERS_DETAILS]
@USER_NAME NVARCHAR(100),
@PASSWORD NVARCHAR(50),
@USER_ADDRESS NVARCHAR(MAX),
@IMAGE_PATH NVARCHAR(MAX) = NULL,
@FULL_NAME NVARCHAR(100),
@ENC_PWD NVARCHAR(MAX),
@STATUS INT OUT,
@MESSAGE NVARCHAR(200) OUT
AS
BEGIN
	BEGIN TRY
		IF NOT EXISTS(SELECT 1 FROM dbo.USERS WHERE USER_NAME = @USER_NAME)
			BEGIN
				INSERT INTO dbo.USERS VALUES(@USER_NAME,@PASSWORD,@ENC_PWD,@USER_ADDRESS,@IMAGE_PATH,@FULL_NAME)
				SET @STATUS = 1
				SET @MESSAGE = 'SUCCESSFULLY INSERTED'
			END
		ELSE
			BEGIN
				SET @STATUS = 0
				SET @MESSAGE = 'DUPLICATE USERNAME'	
			END
	END TRY
	BEGIN CATCH
		SET @STATUS = 0
	END CATCH
END
GO


USE [TestResearchDB]
GO

/****** Object:  StoredProcedure [dbo].[CHECK_LOGIN]    Script Date: 5/15/2024 7:54:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[CHECK_LOGIN]
@USERNAME NVARCHAR(MAX),
@PASSWORD NVARCHAR(MAX),
@HASHPASSWORD NVARCHAR(MAX)

AS
BEGIN
	SELECT ID FROM dbo.USERS WHERE USER_NAME = @USERNAME AND PASSWORD = @PASSWORD AND ENC_PASSWORD = @HASHPASSWORD
END
GO


USE [TestResearchDB]
GO

/****** Object:  StoredProcedure [dbo].[GET_USER_DATA]    Script Date: 5/15/2024 7:54:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[GET_USER_DATA]
@USER_ID INT
AS
BEGIN
	IF(@USER_ID > 0)
		BEGIN
			SELECT USER_NAME, PASSWORD, USER_ADDRESS, UPLOADED_IMG, FULL_NAME FROM dbo.USERS WHERE ID=@USER_ID
		END
	END
GO


USE [TestResearchDB]
GO

/****** Object:  StoredProcedure [dbo].[UPDATE_USER_DETAILS]    Script Date: 5/15/2024 7:54:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [dbo].[UPDATE_USER_DETAILS]
@USER_ID INT,
@USER_NAME NVARCHAR(100),
@PASSWORD NVARCHAR(50),
@USER_ADDRESS NVARCHAR(MAX),
@FULL_NAME NVARCHAR(100),
@ENC_PWD NVARCHAR(MAX),
@IMAGE_PATH NVARCHAR(MAX),
@STATUS INT OUT,
@MESSAGE NVARCHAR(200) OUT
AS
BEGIN
	IF EXISTS(SELECT 1 FROM dbo.USERS WHERE ID = @USER_ID)
		BEGIN
			UPDATE dbo.USERS SET USER_NAME = @USER_NAME, PASSWORD = @PASSWORD, ENC_PASSWORD = @ENC_PWD, USER_ADDRESS = @USER_ADDRESS,
			UPLOADED_IMG = @IMAGE_PATH WHERE ID=@USER_ID
			SET @STATUS = 1
			SET @MESSAGE = 'SUCCESSFULLY UPDATED'
		END
	ELSE
		BEGIN
			SET @STATUS = 0
			SET @MESSAGE = 'FAILED'
		END
END
GO


USE [TestResearchDB]
GO

/****** Object:  StoredProcedure [dbo].[SAVE_SURVEY_HEAD_DETAILS]    Script Date: 5/15/2024 7:55:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SAVE_SURVEY_HEAD_DETAILS]
@JSON_DATA NVARCHAR(MAX),
@STATUS INT OUT,
@MESSAGE NVARCHAR(200) OUT
AS
BEGIN
	BEGIN TRY
		BEGIN TRANSACTION SURVEYTRANSACTION;
		--INSERTING INTO THE HEAD TABLE FIRST
		INSERT INTO dbo.SURVEY_FORM_HEAD(OWNER_NAME, SHOP_NAME, OWNER_EMAIL, ADDRESS, PHONE_NUMBER, SURVEY_USER_ID, SURVEY_DATE)
		SELECT OWNER_NAME, SHOP_NAME, OWNER_EMAIL, ADDRESS, PHONE_NUMBER, SURVEY_USER_ID, GETDATE()
		FROM OPENJSON(@JSON_DATA)
		WITH(
			owner_name NVARCHAR(MAX),
			shop_name NVARCHAR(MAX),
			owner_email NVARCHAR(MAX),
			address NVARCHAR(MAX),
			phone_number NVARCHAR(MAX),
			survey_user_id INT,
			survey_date NVARCHAR(MAX)
		);

		--Get the id of inserted head table
		DECLARE @HEAD_ID BIGINT
		SET @HEAD_ID = SCOPE_IDENTITY();

		--INSERTING DATA INTO DETAILS TABLE
		INSERT INTO dbo.SURVEY_FORM_DETAILS(SURVEY_FORM_HEAD_ID, DEVICE_NAME, DEVICE_CODE, CREATED_DATE) 
		SELECT @HEAD_ID, DEVICE_NAME, DEVICE_CODE, GETDATE()
		FROM OPENJSON(@JSON_DATA, '$.survey_details')
		WITH(
			device_name NVARCHAR(MAX),
			device_code NVARCHAR(MAX)
		);
		COMMIT TRANSACTION SURVEYTRANSACTION;
		SET @STATUS = 1
		SET @MESSAGE = 'SUCCESSFULLY INSERTED'
	END TRY

	BEGIN CATCH
		IF @@TRANCOUNT > 0
		BEGIN
			ROLLBACK TRANSACTION SURVEYTRANSACTION;
			SET @STATUS = 0
			SET @MESSAGE = 'SOMETHING WENT WRONG'
		END
	END CATCH

END
GO


